<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>assets\pause-button-red-icon.ico</ApplicationIcon>
    <Title>Pause batch execution with a timeout</Title>
    <Copyright>Copyright © 2004-{Now:yyyy} Martin Smith</Copyright>
    <Authors>MartinSmith1968</Authors>
    <Company>Martin Smith</Company>
    <Description>A simple app to pause batch execution with a timeout</Description>
    <AssemblyVersion>2.1.0.*</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DNX.Extensions" Version="1.4.25131.2031" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.51.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\pause-button-red-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libs\ConsoleApplications.Common\ConsoleApplications.Common.csproj" />
  </ItemGroup>

</Project>
