<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Platform>x64</Platform>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>assets\text-format.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="assets\text-format.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ookii.CommandLine" Version="5.0.0" />
  </ItemGroup>

</Project>
